name: Spring

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: 17

    - name: Build JAR
      run: |
        chmod +x gradlew
        ./gradlew build -x test

    - name: Build Docker image
      run: docker build -t spring .

    - name: Run container
      run: docker run -d -p 8080:8080 --name spring-container spring

    - name: Install Python
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip3 install requests pytest

    - name: Run Python test
      run: pytest src/test/python/test.py

    - name: Login Dockerhub
      uses: docker/login-action@v2
      with:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Dockerhub
      run: |
        docker tag spring ${{ secrets.DOCKERHUB_USERNAME }}/spring:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring:latest